language: generic
sudo: required

services:
    - docker

before-install:
    - docker build -t artnikitin/udemy-nginx -f Dockerfile.dev .

script:
    - docker run -e CI=true artnikitin/udemy-nginx npm run test